name: Build and Test ContactManager API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Verifica o repositório do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura o .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      # 3. Restaura as dependências
      - name: Restore dependencies
        run: dotnet restore

      # 4. Compila a solução
      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # 5. Executa os testes
      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"
        continue-on-error: false

      # 6. Gera uma mensagem de sucesso
      - name: Ready for deployment message
        if: success()
        run: echo "Tudo certo para o deploy!"
